version: '3.8'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ./:/app:delegated
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: